logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
       defaultZone: ${CONFIG_SERVICE_URL:http://localhost:8761/eureka/}


